<a href="https://colab.research.google.com/github/Psp29onetwo/TensorFlow_101/blob/main/00_TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundamentals of tensors using TensorFlow.
In this notebook we cover some of the most fundamental TensorFlow operations, more specificially:

* Introduction to tensors (creating tensors)
* Getting information from tensors (tensor attributes)
* Manipulating tensors (tensor operations)
* Tensors and NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow
* Exercises to try

# Importing TensorFlow

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.5.0


def constant(value, dtype=None, shape=None, name='Const')
Creates a constant tensor from a tensor-like object.

Note: All eager tf.Tensor values are immutable (in contrast to
tf.Variable). There is nothing especially _constant_ about the value
returned from tf.constant. This function is not fundamentally different from
tf.convert_to_tensor. The name tf.constant comes from the value being
embedded in a Const node in the tf.Graph. tf.constant is useful
for asserting that the value can be embedded that way.

If the argument dtype is not specified, then the type is inferred from
the type of value.

>>> # Constant 1-D Tensor from a python list.
>>> tf.constant([1, 2, 3, 4, 5, 6])
<tf.Tensor: shape=(6,), dtype=int32,
    numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>
>>> # Or a numpy array
>>> a = np.array([[1, 2, 3], [4, 5, 6]])
>>> tf.constant(a)
<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
  array([[1, 2, 3],
         [4, 5, 6]])>
If dtype is specified, the resulting tensor values are cast to the requested
dtype.

>>> tf.constant([1, 2, 3, 4, 5, 6], dtype=tf.float64)
<tf.Tensor: shape=(6,), dtype=float64,
    numpy=array([1., 2., 3., 4., 5., 6.])>
If shape is set, the value is reshaped to match. Scalars are expanded to
fill the shape:

>>> tf.constant(0, shape=(2, 3))
  <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
  array([[0, 0, 0],
         [0, 0, 0]], dtype=int32)>
>>> tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
  array([[1, 2, 3],
         [4, 5, 6]], dtype=int32)>
tf.constant has no effect if an eager Tensor is passed as the value, it
even transmits gradients:

>>> v = tf.Variable([0.0])
>>> with tf.GradientTape() as g:
...     loss = tf.constant(v + v)
>>> g.gradient(loss, v).numpy()
array([2.], dtype=float32)
But, since tf.constant embeds the value in the tf.Graph this fails for
symbolic tensors:

>>> with tf.compat.v1.Graph().as_default():
...   i = tf.compat.v1.placeholder(shape=[None, None], dtype=tf.float32)
...   t = tf.constant(i)
Traceback (most recent call last):
...
TypeError: ...
tf.constant will _always_ create CPU (host) tensors. In order to create
tensors on other devices, use tf.identity. (If the value is an eager
Tensor, however, the tensor will be returned unmodified as mentioned above.)

Related Ops:


tf.convert_to_tensor is similar but:

It has no shape argument.

Symbolic tensors are allowed to pass through.




>>> with tf.compat.v1.Graph().as_default():
...   i = tf.compat.v1.placeholder(shape=[None, None], dtype=tf.float32)
...   t = tf.convert_to_tensor(i)

tf.fill: differs in a few ways:

tf.constant supports arbitrary constants, not just uniform scalar
Tensors like tf.fill.

tf.fill creates an Op in the graph that is expanded at runtime, so it
can efficiently represent large tensors.

Since tf.fill does not embed the value, it can produce dynamically
sized outputs.




Args:
  value: A constant value (or list) of output type dtype.
  dtype: The type of the elements of the resulting tensor.
  shape: Optional dimensions of resulting tensor.
  name: Optional name for the tensor.

Returns:
  A Constant Tensor.

Raises:
  TypeError: if shape is incorrectly specified or unsupported.
  ValueError: if called on a symbolic tensor.

In [ ]:
# creating tensor with tf.constant()
scalar = tf.constant(29)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=29>

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([29, 29])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([29, 29], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# crate a matrix
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# create another matrix
another_martrix = tf.constant([[29, 38],
                              [38, 29],
                              [45, 47]], dtype = tf.float16) #specify dType with parameter
another_martrix                          

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[29., 38.],
       [38., 29.],
       [45., 47.]], dtype=float16)>

In [ ]:
another_martrix.ndim

2

In [ ]:
# crate tensor
tensor = tf.constant([[[1, 2, 3],
                       [3, 4, 5]],
                      [[4, 5, 6],
                       [7, 8, 9]],
                      [[10, 11, 12],
                       [13, 14, 15]]]) # hard to read eh? too many brackets and coomas :(
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15]]], dtype=int32)>

In [ ]:
tensor.ndim

3

## Crating Tensors with `tf.Variable` :)

In [ ]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's change values of this tensors
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

#Creating random tensors

## Random tensors are tensors of some arbitary size which contains random numbers

In [ ]:
random_1 = tf.random.Generator.from_seed(38)
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(38)
random_2 = random_2.normal(shape=(3, 2))
random_1, random_2, random_1 == random_2 #Looks like we've created tensors with random values but in real this are just psuedo random numbers that's why i use from_seed(`number`) to generate pseudo random number with same seed

### shuffle the order of elements in a tensor

In [ ]:
# shuffle the tensor( used when you want to shuffle the data so the inherent order doesn't affect learning)
not_shuffled = tf.constant([[10, 7],
                            [29, 38],
                            [45, 47]])
not_shuffled, not_shuffled.ndim

In [ ]:
# Shuffle our tensor
tf.random.set_seed(29) # global random seed
tf.random.shuffle(not_shuffled) # will produce same value everytime coz of global random seed

In [ ]:
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2' # getting different value because ther is no global random seed

In [ ]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2' # getting same value because of global random seed

In [ ]:
tf.random.set_seed(1234)

@tf.function
def f():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

@tf.function
def g():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

print(f())  # prints '(A1, A2)'
print(g())  # prints '(A1, A2)'

In [ ]:
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

In [ ]:
@tf.function
def foo():
  a = tf.random.uniform([1], seed=1)
  b = tf.random.uniform([1], seed=1)
  return a, b
print(foo())  # prints '(A1, A1)'
print(foo())  # prints '(A2, A2)'

@tf.function
def bar():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b
print(bar())  # prints '(A1, A2)'
print(bar())  # prints '(A3, A4)'

In [ ]:
## create a tensor of all ones
tf.ones([10, 7], dtype=tf.int32) # by default it generate tf.float32

In [ ]:
# create a tensor of all zeros
tf.zeros([10, 7], dtype=tf.int32) # by default it generate tf.float32

### Turn Numpy arrays into tensors
TensorFlow tensors can run much faster on GPU

In [ ]:
# converting numpy arrays in to tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
A

In [ ]:
2 * 3 * 4

There will be times when you'll want to get different pieces of information from your tensors, in particuluar, you should know the following tensor vocabulary:

* Shape: The length (number of elements) of each of the dimensions of a tensor.
* Rank: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
* Axis or Dimension: A particular dimension of a tensor.
* Size: The total number of items in the tensor.

In [ ]:
# rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

In [ ]:
rank_4_tensor[0]

In [ ]:
rank_4_tensor[0][1]

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

In [ ]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

## Indexing the tensors

In [ ]:
# Get first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

In [ ]:
# Create rank 2 tensor
rank_2_tensor = tf.constant([[3, 4],
                             [5, 6]])
rank_2_tensor

In [ ]:
rank_2_tensor[:, -1]

In [ ]:
# adding dimension to rank_2_tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

# Matrix mutliplication
The main two rules for matrix multiplication to remember are:

1. The inner dimensions must match:
  * (3, 5) @ (3, 5) won't work
  * (5, 3) @ (3, 5) will work
  * (3, 5) @ (5, 3) will work
2. The resulting matrix has the shape of the inner dimensions:
  * (5, 3) @ (3, 5) -> (3, 3)
  * (3, 5) @ (5, 3) -> (5, 5)

In [ ]:
a = tf.constant([[1, 2, 5],
                 [7, 2, 1],
                 [3, 3, 3]])
b = tf.constant([[3, 5],
                 [6, 7],
                 [1, 8]])

print(a, b, "\n")
a.shape, b.shape

In [ ]:
tf.matmul(a, b)

In [ ]:
# matrix multiplication with python operator
a @ b

In [ ]:

# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

In [ ]:
tf.matmul(X, Y)

In [ ]:
X.shape, Y.shape

In [ ]:
X.shape, tf.reshape(Y, shape=(2, 3)).shape

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

In [ ]:
tf.matmul(tf.reshape(X, shape=(2, 3)), Y)

## The DOT product
Multiplying matrices by eachother is also referred to as the dot product.

You can perform the `tf.matmul()` operation using `tf.tensordot()`.

In [ ]:
X, Y

In [ ]:
tf.tensordot(tf.transpose(X), Y, axes=1)

# Changing the datatype of a tensor
Sometimes you'll want to alter the default datatype of your tensor.

This is common when you want to compute using less precision (e.g. 16-bit floating point numbers vs. 32-bit floating point numbers).

Computing with less precision is useful on devices with less computing capacity such as mobile devices (because the less bits, the less space the computations require).

You can change the datatype of a tensor using tf.cast().

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])

# Create a new tensor with default datatype (int32)
C = tf.constant([1, 7])
B, C

In [ ]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B

In [ ]:
# Change from int32 to float32
C = tf.cast(C, dtype=tf.float32)
C

In [ ]:
# Change from int32 to int32
A = tf.cast(C, dtype=tf.int16)
A

In [ ]:
# Change from float32 to int32
E = tf.cast(B, dtype=tf.int32)
E

# Aggregating Tensors

In [ ]:
D = tf.constant([-29, -38])
D

In [ ]:
tf.abs(D)

#Finding the min, max, mean, sum (aggregation)
You can quickly aggregate (perform a calculation on a whole tensor) tensors to find things like the minimum value, maximum value, mean and sum of all the elements.

To do so, aggregation methods typically have the syntax reduce()_[action], such as:

* tf.reduce_min() - find the minimum value in a tensor.
* tf.reduce_max() - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).
* tf.reduce_mean() - find the mean of all elements in a tensor.
* tf.reduce_sum() - find the sum of all elements in a tensor.
* Note: typically, each of these is under the math module, e.g. tf.math.reduce_min() but you can use the alias tf.reduce_min().
Let's see them in action.

In [ ]:
import numpy as np

In [ ]:
# creating random tensor (large)
E = tf.constant(np.random.randint(0, 100, size = 50))
E

In [ ]:
tf.size(E), E.shape, E.ndim

In [ ]:
# Find minimum
tf.reduce_min(E)

In [ ]:
# Find maximum
tf.reduce_max(E)

In [ ]:
# Find the mean
tf.reduce_mean(E)

In [ ]:
# Find the sum
tf.reduce_sum(E)

In [ ]:
# Find the variance
tf.nn.moments(E, axes=0)

In [ ]:
# Another method to find variance
import tensorflow_probability as tfp

In [ ]:
tfp.stats.variance(E) #1 method note: vairance in int

In [ ]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float16)) #2 method note: vairance in float

In [ ]:
# Find the standard Deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float16)) # or tf.float32 will do with double memory consumption

In [ ]:
# want to use bash?
!bash

In [ ]:
# Find the positional maximum and minimum
tf.random.set_seed(29)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.22340703, 0.39183307, 0.22348964, 0.2816745 , 0.94804025,
       0.79663575, 0.66978335, 0.5309613 , 0.75650704, 0.3351189 ,
       0.9920033 , 0.1204809 , 0.58007467, 0.38786924, 0.32651854,
       0.3815912 , 0.43200243, 0.1508205 , 0.24685323, 0.49803722,
       0.37090683, 0.11783051, 0.5026778 , 0.9324962 , 0.61422026,
       0.59533   , 0.9282651 , 0.16858912, 0.7827904 , 0.4166478 ,
       0.15587008, 0.4053272 , 0.11497223, 0.81684244, 0.9850751 ,
       0.82948864, 0.06480718, 0.56691587, 0.6045724 , 0.55613196,
       0.7914666 , 0.11840737, 0.7078321 , 0.5141301 , 0.56695807,
       0.60106146, 0.11790371, 0.34143245, 0.36056364, 0.33962345],
      dtype=float32)>

In [ ]:
# positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=10>

In [ ]:
# index on our largest value positional
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9920033>

In [ ]:
# max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9920033>

In [ ]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=36>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.06480718>

# sqeezing a tensor (removing all single dimensions)

In [ ]:
# create a tensor
tf.random.set_seed(29)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.22340703, 0.39183307, 0.22348964, 0.2816745 , 0.94804025,
           0.79663575, 0.66978335, 0.5309613 , 0.75650704, 0.3351189 ,
           0.9920033 , 0.1204809 , 0.58007467, 0.38786924, 0.32651854,
           0.3815912 , 0.43200243, 0.1508205 , 0.24685323, 0.49803722,
           0.37090683, 0.11783051, 0.5026778 , 0.9324962 , 0.61422026,
           0.59533   , 0.9282651 , 0.16858912, 0.7827904 , 0.4166478 ,
           0.15587008, 0.4053272 , 0.11497223, 0.81684244, 0.9850751 ,
           0.82948864, 0.06480718, 0.56691587, 0.6045724 , 0.55613196,
           0.7914666 , 0.11840737, 0.7078321 , 0.5141301 , 0.56695807,
           0.60106146, 0.11790371, 0.34143245, 0.36056364, 0.33962345]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.22340703, 0.39183307, 0.22348964, 0.2816745 , 0.94804025,
       0.79663575, 0.66978335, 0.5309613 , 0.75650704, 0.3351189 ,
       0.9920033 , 0.1204809 , 0.58007467, 0.38786924, 0.32651854,
       0.3815912 , 0.43200243, 0.1508205 , 0.24685323, 0.49803722,
       0.37090683, 0.11783051, 0.5026778 , 0.9324962 , 0.61422026,
       0.59533   , 0.9282651 , 0.16858912, 0.7827904 , 0.4166478 ,
       0.15587008, 0.4053272 , 0.11497223, 0.81684244, 0.9850751 ,
       0.82948864, 0.06480718, 0.56691587, 0.6045724 , 0.55613196,
       0.7914666 , 0.11840737, 0.7078321 , 0.5141301 , 0.56695807,
       0.60106146, 0.11790371, 0.34143245, 0.36056364, 0.33962345],
      dtype=float32)>

# One Hot Encoding

In [ ]:
# create a list of indices
some_list = [0, 1, 2, 3] #could be green, red, blue, purple
tf.one_hot(some_list, depth=4) # depth should be equal to the elemenets in the data


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="YO!" , off_value="#PSP") #on_value and off_value dtype should be same

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'YO!', b'#PSP', b'#PSP', b'#PSP'],
       [b'#PSP', b'YO!', b'#PSP', b'#PSP'],
       [b'#PSP', b'#PSP', b'YO!', b'#PSP'],
       [b'#PSP', b'#PSP', b'#PSP', b'YO!']], dtype=object)>

In [ ]:
some_list

[0, 1, 2, 3]

In [ ]:
# changing the depth
tf.one_hot(some_list, depth=8) # if depth is large than requirement than all zeros will be output after one hot encoding

<tf.Tensor: shape=(4, 8), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list, depth=3) # if depth is less than requirement than one hot encoding will be affected

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list, depth=4, axis=0)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

# Tensors and Numpy

In [ ]:
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# convert our tensor to numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# convert tensor J to a numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# the default dtype of both are different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
# check the dtypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

# Finding access to GPU's

In [ ]:
import tensorflow as tf

tf.config.list_physical_devices(), tf.config.list_physical_devices("GPU")

([PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
  PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')],
 [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')])

In [ ]:
!nvidia-smi # to check which GPU we are using

Sun Jul  4 05:57:19 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.27       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## 🛠 Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
7. Find the min and max values of the tensor you created in 6.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

## 📖 Extra-curriculum

* Read through the [list of TensorFlow Python APIs](https://www.tensorflow.org/api_docs/python/), pick one we haven't gone through in this notebook, reverse engineer it (write out the documentation code for yourself) and figure out what it does.
* Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
  * How would you calculate your grocery bill for the month and for the year using tensors?
* Go through the [TensorFlow 2.x quick start for beginners](https://www.tensorflow.org/tutorials/quickstart/beginner) tutorial (be sure to type out all of the code yourself, even if you don't understand it).
  * Are there any functions we used in here that match what's used in there? Which are the same? Which haven't you seen before?
* Watch the video ["What's a tensor?"](https://www.youtube.com/watch?v=f5liqUk0ZTw) - a great visual introduction to many of the concepts we've covered in this notebook.